### ISSUE TITLE
运行代码，pose点会有很多重复

### ISSUE THREAD

**Issue by lofyol** [cqu20160901/yolov8pose_dfl_rknn_Cplusplus#3]
在python下测试，多个人都能够有对应的关键点，但是C++下多个人只是框正确，点都是同一个人的，请问下啥原因造成的

**Comment by cqu20160901** [comment]
问题已解决，同步一下代码。

**Comment by cqu20160901** [comment]
![image](https://github.com/user-attachments/assets/a12ade93-fe6f-4d1d-9c6b-62fe1d28ef46)
